README.rst

docs: addition of license and chat room badges

---

.travis.yml
README.rst

* Adds initial Travis CI configuration, checking commit log kwalitee
only so far.  (closes #1)

travis: initial release of CI configuration

---

.editorconfig
.gitignore
THANKS.rst
claimstore/app.py
claimstore/core/decorators.py
claimstore/core/exception.py
claimstore/core/json.py
claimstore/modules/claims/models.py
claimstore/modules/claims/restful.py
claimstore/modules/claims/views.py
claimstore/static/css/base.css
claimstore/static/css/docs.css
claimstore/static/js/lib/jsoneditor.js
claimstore/static/json/examples/claim.cds.1.json
claimstore/static/json/examples/claim.inspire.1.json
claimstore/static/json/examples/claimant.cds.json
claimstore/static/json/examples/claimant.inspire.json
claimstore/static/json/schemas/claims/claim.json
claimstore/static/json/schemas/claims/claimant.json
claimstore/templates/404.html
claimstore/templates/api.html
claimstore/templates/base.html
claimstore/templates/contact.html
claimstore/templates/cover.html
claimstore/templates/subscription.html
claimstore/wsgi.py
requirements.txt
run.py

* Adds initial prototype code, it will be refactored later. (closes #3)

global: initial prototype

---

claimstore/__init__.py
claimstore/app.py
claimstore/core/__init__.py
claimstore/core/decorators.py
claimstore/core/exception.py
claimstore/core/json.py
claimstore/modules/__init__.py
claimstore/modules/claims/__init__.py
claimstore/modules/claims/models.py
claimstore/modules/claims/restful.py
claimstore/modules/claims/views.py
claimstore/static/css/base.css
claimstore/static/css/docs.css
claimstore/templates/404.html
claimstore/templates/api.html
claimstore/templates/base.html
claimstore/templates/contact.html
claimstore/templates/cover.html
claimstore/templates/subscription.html
claimstore/wsgi.py
run.py

Added license headers and fixed some PEP8.

12 license headers

---

claimstore/__init__.py
claimstore/app.py
claimstore/core/__init__.py
claimstore/core/decorators.py
claimstore/core/exception.py
claimstore/core/json.py
claimstore/modules/__init__.py
claimstore/modules/claims/__init__.py
claimstore/modules/claims/models.py
claimstore/modules/claims/restful.py
claimstore/modules/claims/views.py
claimstore/wsgi.py
run.py

* Improve PEP-257 compliance. (closes #16)

docs: PEP-257 compliance

---

claimstore/app.py
claimstore/core/decorators.py
claimstore/core/json.py
claimstore/modules/claims/models.py
claimstore/modules/claims/restful.py
claimstore/modules/claims/views.py
claimstore/wsgi.py
run.py

* Complies with correct import order

global: import order compliance

---

.coveragerc
.dockerignore
.gitignore
.travis.yml
Dockerfile
README.rst
claimstore/app.py
claimstore/core/json.py
claimstore/modules/claims/models.py
claimstore/modules/claims/restful.py
claimstore/modules/claims/views.py
claimstore/version.py
pytest.ini
requirements.txt
run-tests.sh
setup.py
tests/test_core_json.py
tox.ini

- e005af9bdcda54f4d7a37b4c354ad19348b2c159 tests: initial release of infrastructure
- 2c12d6efde11e06ed66c62a8b8dfedce7d5f7e03 global: import order re-fix

21-basic-testing-infrastructure

---

claimstore/modules/claims/restful.py
claimstore/templates/api.html
tests/test_restful_api.py

api: new resource in order to list identifiers

---

claimstore/app.py
claimstore/core/datetime.py
claimstore/core/exception.py
claimstore/core/json.py
claimstore/modules/claims/models.py
claimstore/modules/claims/restful.py
claimstore/modules/claims/views.py

* Enriches docstrings globally. (closes #37)

docs: enriched docstrings

---

README.rst
docs/index.rst

* Adds installation, testing and documentation section to the project
README file.

docs: richer project README

---

README.rst
setup.py

global: more GNU GPLv3 amendments

---

.kwalitee.yml
claimstore/modules/claims/templates/claims/base.html

templates: fix ClaimStore footer link

---

claimstore/modules/claims/fixtures/predicate.py
claimstore/modules/claims/restful.py
claimstore/modules/claims/static/json/examples/claim.inspire.2.json
claimstore/modules/claims/static/json/schemas/claim.json
docs/design.rst
tests/test_restful_api.py

* Updates the initial predicates that will be used in ClaimStore.
(closes #8)

api: updated predicates

---

claimstore/modules/claims/restful.py
claimstore/modules/claims/static/json/examples/claim.cds.1.json
claimstore/modules/claims/static/json/examples/claim.inspire.1.json
claimstore/modules/claims/static/json/examples/claim.inspire.2.json
claimstore/modules/claims/static/json/schemas/claim.json
docs/description.rst

* Cleans JSON schema for claims. (closes #51, closes #4)

global: cleaned claims JSON format

---

claimstore/modules/claims/restful.py

* Fixes a bug due to a wrong argument when raising a RESTful exception.
(closes #56)

api: fixed bug when raising exception

---

.travis.yml
Dockerfile
pytest.ini
setup.py

* Fixes compatibility with latest pytest. (closes #75)

tests: compatibility fix for latest pytest

---

claimstore/modules/claims/cli.py
claimstore/modules/claims/fixtures/decorator.py
claimstore/testing/fixtures/app.py
tests/test_cli_claims.py
tests/test_eq_ids.py
tests/test_restful_api.py

* Adds new tests cases in order to test the click commands. (closes #68)

tests: add click command test cases

---

Dockerfile
README.rst
docker-compose.yml
docs/installation.rst

* Fixes (and simplifies) Docker installation instructions. (closes #67)

docker: installation instruction fix

---

docs/users.rst

docs: cosmetic cleanup of RESTful documentation

---

docker-compose-prod.yml

docker: leftover removal from `prod` compose

---

claimstore/core/json.py
claimstore/restful.py
docs/design.rst

tests: isort vs flake8 import order differences
